name: abstract_sync
description: An package implementing a syncing algorithm suitable for any backend.
version: 1.0.0
homepage: https://github.com/saber-notes/abstract_sync

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
