name: abstract_sync
description: A framework for writing your own syncing solution.
version: 0.0.1
homepage: https://github.com/saber-notes/abstract_sync

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.0.0

  meta: ^1.12.0

  mutex: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
