name: abstract_sync
description: A framework for writing your own syncing solution between any two sources.
version: 1.2.0
homepage: https://github.com/saber-notes/abstract_sync

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logging: ^1.0.0

  meta: ^1.12.0

  mutex: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
